### ISSUE TITLE
After installation web client shows "Mopidy-Spotify extension is not running"

### ISSUE THREAD

**Issue by Rocketansky** [pimoroni/pirate-audio#12]
After I got the installation correct I investigated the iris client.
Clicking on the settings for Spotify I saw an orange bar with "Mopidy-Spotify extension is not running  - you will not be able to play any Spotify tracks"
![image](https://user-images.githubusercontent.com/25251718/71835112-13ef0e80-30b1-11ea-9ed3-54ab13208f0e.png)

**Comment by docmollo** [comment]
Sounds like you don't have the spotify plugin enabled. Check the spotify section of your config file. By default, the plugin is set to disabled (false).

**Comment by Rocketansky** [comment]
@docmollo Thanks! I changed the value in file /etc/mopidy/mopidy.conf and it worked.

Should be part of some documentation - IMO

**Comment by derekslenk** [comment]
I am also having this issue. However, I have enabled spotify in the mopidy.conf

Do we need to generate all the tokens for the plugin or is the web interface supposed to take care of that?
