### ISSUE TITLE
Radio Text not shown in Display

### ISSUE THREAD

**Issue by ingelumer** [pimoroni/pirate-audio#24]
When running a Radio Stream in Mopidy I can see the Radio Text in my web browser GUI like Title and Interpret (actually also in the Mopidy Mobile Android App), but the PirateAudio Display does only show the Radio Station name.
Would it be possible to show additional Information for Radio Steams just like for playing MP3/Spotify?

**Comment by ingelumer** [comment]
just realized that when mentioning the WebGUI, Iris is not showing the Information as well, but musicbox_webclient does.

**Comment by Gadgetoid** [comment]
Try `sudo pip3 install --upgrade mopidy-pidi` and see if the new release works for you.

**Comment by ingelumer** [comment]
Looks indeed much better, thanks for the hint!
I can see the Artist and Title now, but the Radio Station Name is gone :-(
