### ISSUE TITLE
Screen saver

### ISSUE THREAD

**Issue by JayGatsby7** [pimoroni/pirate-audio#25]
I run mopidy and iris 24x7 - is there any way to turn off the screen when it is not in active use?

**Comment by remmelt** [comment]
Or dim the screen somehow?

**Comment by kokosowy** [comment]
Yeah I also vote for dimming. Does this hardware allows to turn off the backlight? Thanks in advance!

**Comment by duracell80** [comment]
This might be worth a try.

https://github.com/dandydanny/PiAutoDim/blob/master/autobrightness.py


```
# Open backlight control 'file' for writing
f = open('/sys/class/backlight/rpi_backlight/brightness', 'w')

```

**Comment by Gadgetoid** [comment]
This should be possible - on the Pirate Audio board LCDs at least - as of https://github.com/pimoroni/mopidy-pidi/pull/17
