### ISSUE TITLE
X-Y Buttons not working

### ISSUE THREAD

**Issue by rnsi** [pimoroni/pirate-audio#38]
Using Pirate Audio to roll my own player.

X and Y buttons don't work for me on a Pi Zero W. Fixed it by adding this to /boot/config.txt:

gpio=16=ip,pu
gpio=20=ip,pu

Depending on your board, you may need to use gpio 24 rather than 20.

Hope this helps someone else.

**Comment by duracell80** [comment]
That's helpful yeah, thank you. I wonder if there's a version number of the boards which this check could be automated against.

**Comment by duracell80** [comment]
https://www.hifiberry.com/docs/hardware/gpio-usage-of-hifiberry-boards/

 GPIOs 18-21 (pins 12, 35, 38 and 40) are used for the sound interface. You can’t use them for any other purpose.
