### ISSUE TITLE
Pirate Audio / Raspberry Pi 0 with mopidy, raspotify, upmpdcli

### ISSUE THREAD

**Issue by semhoun** [pimoroni/pirate-audio#41]
Hello,

I have some difficulties to make Pirate Audio working on Raspberry Pi 0 with mopidy, raspotify, upmpdcli, samba and usbmount.

I do a script to install/reinstall my devices, and share it maybe it can help someone: https://gist.github.com/semhoun/926334fcc56fea82d988851c5a6e53ac

**Comment by snarflakes** [comment]
does your script work (enable all functionality for all the software?) mopidy was a mess the first time i tried it and I'm kind of stuck. i can't even play mp3.  on the pirate audio, sounds comes out all crackly.1

**Comment by semhoun** [comment]
> does your script work (enable all functionality for all the software?) mopidy was a mess the first time i tried it and I'm kind of stuck. i can't even play mp3. on the pirate audio, sounds comes out all crackly.1

I try it on 2 different kit. The only bug I have is on the /etc/asound.conf conf who I have to apply two time on one kit before having PCM mixer running (maybe I forgot an empty line at the end of the file).

**Comment by snarflakes** [comment]
There is some conflict in mine, mopidy only works if i kill process APLAY every time I reboot or restart. So i am looking for someone elses.  I have a raspberry pi zero wh.
