### ISSUE TITLE
stuttering audio

### ISSUE THREAD

**Issue by mds101** [pimoroni/pirate-audio#42]
Since the last Raspberry Pi OS Update last week, the sound out of my Pirate Audio Line out is stuttering, with every source I've tried. (MPD, VLC, Kodi, Youtube). If I switch the audio output to HDMI, the sound is ok.
The sound was ok with the Pulse Audio update. 
I haven't touch the PulseAudio daemon.conf
Any idea?

**Comment by rigelinorion** [comment]
I join the question. I'm using mpd and mpc for playback. The program loops when opening an Internet Radio stream. Sometimes it helps to restart the system, sometimes it doesn't.
