### ISSUE TITLE
pirate audio clip recorder

### ISSUE THREAD

**Issue by Mjd1974** [pimoroni/pirate-audio#44]
Hi,

I'm having trouble getting my pirate audio dual mic up and running. I have started with a fresh install of raspberry pi os on a 16gb sd card and on a pi3. The os has installed fine. 

I downloaded pirate audio and installed the clip recorder using:

git clone https://github.com/pimoroni/pirate-audio
cd pirate-audio/clip-recorder
sudo ./install.sh

The process seems to run fine but I've tried several times and the pirate audio hat does not respond. It lights up but no display. There are no error messages that I can see to post on here. I can see pirate audio in the file manager but not in the application menu. Happy to share more information if anyone can point me in the right direction. 

Thanks

**Comment by Gadgetoid** [comment]
I think there are a couple of ways to trip up with the clip recorder installer that I've hopefully fixed in - https://github.com/pimoroni/pirate-audio/pull/60

More discussion in - https://github.com/pimoroni/pirate-audio/issues/37
