### ISSUE TITLE
Wrong with scan 

### ISSUE THREAD

**Issue by ZHUOJIAGAO** [pimoroni/pirate-audio#53]
When I run the scan command, it will display unrecognized command: local.

![1618446132](https://user-images.githubusercontent.com/79019980/114796519-1991d480-9d89-11eb-9c4e-266cfe13a17e.png)

**Comment by kokosowy** [comment]
Hi,

I believe you should use mopidyctl command instead:
sudo mopidyctl local scan

If it says local is unavailable check with pip whether mopidy-local is installed.

**Comment by Gadgetoid** [comment]
Is this mentioned anywhere in our tutorials/guides? Can't tell if this is an us issue or a Mopidy issue.

**Comment by kokosowy** [comment]
It's rather human mistake -- see 'Scanning local media' chapter of https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-pirate-audio.
