### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [pimoroni/pirate-audio#61]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by Gadgetoid** [comment]
Yes and yes. Our code is usually MIT licensed so I suspect the same would apply here. I'll get the file added when I can.

**Comment by Gadgetoid** [comment]
Done!

**Comment by vazhnov** [comment]
MIT License — cool! Thank you!
