### ISSUE TITLE
Display goes off after ~1 Minute

### ISSUE THREAD

**Issue by ingelumer** [pimoroni/pirate-audio#69]
Hello there,
I have run a new installation (Raspbian and PirateAudio) and realized that the screen of the PirateAudio Display goes black after aprox 1 Minute.
However the Player is still running and playing Music, also the Buttons near the Displays still work.
Is this something like screensaver, can I switch it off?

**Comment by Gadgetoid** [comment]
Do you have an "idle_timeout = 60" in "/etc/mopidy/mopidy.conf"?

**Comment by haluskz79** [comment]
Just to add, "idle_timeout=..." parameter has to be in "[pidi]" section in "/etc/mopidy/mopidy.conf"
