### ISSUE TITLE
Manual steps refers to package that doesn't exist

### ISSUE THREAD

**Issue by jodal** [pimoroni/pirate-audio#7]
The manual installation steps asks you to install `mopidy-iris` using `apt`. However, this extension isn't packaged as a Debian package.

The manual steps must be updated to use `pip install mopidy-iris`, like the `install.sh` script does.

**Comment by Gadgetoid** [comment]
Should finally be fixed in https://github.com/pimoroni/pirate-audio/commit/f8b8c54f7b006708d49db15da387bba7065d874e but I used the web API (naughty me) and flubbed the commit before I managed to type #7.
