### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by danielo515** [pimoroni/pirate-audio#70]
Hello.
Thanks for this great project. Installation was super easy.
However, I tried it on a pi that I had around for another role, just to check that my hardware works and now I want to uninstall it.
Could you provide uninstall instructions? Is it enough to disable services and then just delete the folder? Or how?

Thanks in advance

**Comment by Gadgetoid** [comment]
There are quite a few disparate projects contained here- which one(s) did you install?

In most cases- yes- it will suffice to disable the services, but removing software is a little trickier since some of this stuff is a spaghetti of dependencies.
